# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointx', models.CharField(max_length=50, verbose_name='X')),
                ('pointy', models.CharField(max_length=50, verbose_name='Y')),
                ('mdate', models.CharField(max_length=50, verbose_name='日期')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=30, verbose_name='用户')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('img', models.CharField(max_length=120, verbose_name='主图')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='用户')),
                ('mk_id', models.CharField(max_length=120, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
